### ISSUE TITLE
unexpected failure of obc_tests

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy-mobile#2137]
https://github.com/envoyproxy/envoy-mobile/runs/5744148680?check_suite_focus=true

INFO: Repository bazel_gazelle_go_repository_tools instantiated at:
38
  /Users/runner/work/envoy-mobile/envoy-mobile/WORKSPACE:40:25: in <toplevel>
39
  /private/var/tmp/_bazel_runner/b225883c33850f3f191a570e7b70ec29/external/envoy/bazel/dependency_imports.bzl:21:25: in envoy_dependency_imports
40
  /private/var/tmp/_bazel_runner/b225883c33850f3f191a570e7b70ec29/external/bazel_gazelle/deps.bzl:75:24: in gazelle_dependencies
41
Repository rule go_repository_tools defined at:
42
  /private/var/tmp/_bazel_runner/b225883c33850f3f191a570e7b70ec29/external/bazel_gazelle/internal/go_repository_tools.bzl:117:38: in <toplevel>
43
ERROR: An error occurred during the fetch of repository 'bazel_gazelle_go_repository_tools':
44
   Traceback (most recent call last):
45
	File "/private/var/tmp/_bazel_runner/b225883c33850f3f191a570e7b70ec29/external/bazel_gazelle/internal/go_repository_tools.bzl", line 103, column 13, in _go_repository_tools_impl
46
		fail("failed to build tools: " + result.stderr)
47
Error in fail: failed to build tools: Timed out
48
ERROR: /Users/runner/work/envoy-mobile/envoy-mobile/WORKSPACE:40:25: fetching go_repository_tools rule //external:bazel_gazelle_go_repository_tools: Traceback (most recent call last):
49
	File "/private/var/tmp/_bazel_runner/b225883c33850f3f191a570e7b70ec29/external/bazel_gazelle/internal/go_repository_tools.bzl", line 103, column 13, in _go_repository_tools_impl
50
		fail("failed to build tools: " + result.stderr)
51
Error in fail: failed to build tools: Timed out
52
ERROR: /private/var/tmp/_bazel_runner/b225883c33850f3f191a570e7b70ec29/external/com_envoyproxy_protoc_gen_validate/BUILD:18:11: no such package '@com_github_lyft_protoc_gen_star//': no such package '@bazel_gazelle_go_repository_config//': no such package '@bazel_gazelle_go_repository_tools//': failed to build tools: Timed out and referenced by '@com_envoyproxy_protoc_gen_validate//:protoc-gen-validate_lib'
53
ERROR: Analysis of target '//test/objective-c:envoy_bridge_utility_test' failed; build aborted: 
54
INFO: Elapsed time: 1055.588s
55
INFO: 0 processes.
56
FAILED: Build did NOT complete successfully (161 packages loaded, 10678 targets configured)
57
ERROR: Couldn't start the build. Unable to run tests
58
FAILED: Build did NOT complete successfully (161 packages loaded, 10678 targets configured)
59
INFO: Streaming build results to: https://envoy.cluster.engflow.com/invocation/8d667ce4-63f4-4b7d-a38f-4c7ac804e147
60
FAILED: Build did NOT complete successfully (161 packages loaded, 10678 targets configured)
61

62
Error: Process completed with exit code 1.

**Comment by ulfjack** [comment]
It's a terrible error message. My theory is that it's pulling a part of the bazel-gazelle integration from a random place on the internet that was temporarily unavailable (it would be great for Bazel to tell us *which* place). I think caching the files in a more reliable place might help - coincidentally, I recently worked on something that we may be able to use here, once it's production ready.

**Comment by alyssawilk** [comment]
Yeah, a lot of the EM CI failures I've seen have either been flaky tests (which we'll work more on) or fetch fails.  If we can cache more files that'd be fantastic!
